apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notebook-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /notebook
            pathType: Prefix
            backend:
              service:
                name: notebook
                port:
                  number: 8080 