apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebook-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: nb
  hostPath:
    path: /mnt/data/notebook
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notebook-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nb
  resources:
    requests:
      storage: 1Gi